"""update permission parts

Revision ID: abdda4c34580
Revises: 90d301d41052
Create Date: 2025-03-21 11:16:51.860076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abdda4c34580'
down_revision: Union[str, None] = '90d301d41052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('permissions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('permissions', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=True)
    op.drop_column('permissions', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.alter_column('permissions', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('permissions', 'updated_at')
    op.drop_column('permissions', 'created_at')
    # ### end Alembic commands ###
