"""update refresh and expire token date

Revision ID: e8ca056ad005
Revises: 83b8d3be8393
Create Date: 2025-03-18 15:08:49.781819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8ca056ad005'
down_revision: Union[str, None] = '83b8d3be8393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('access_expires_at', sa.DateTime(), nullable=False))
    op.add_column('tokens', sa.Column('refresh_expires_at', sa.DateTime(), nullable=False))
    op.drop_column('tokens', 'expires_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('tokens', 'refresh_expires_at')
    op.drop_column('tokens', 'access_expires_at')
    # ### end Alembic commands ###
